sudo: required

services:
  - docker

env:
  global:
    - REGISTRY_USER=kalemena
    - secure: "X44WfGqsa8NSL80vLWzqvCjxK/03I0CvTmENY10c4WVTRgVUGsXCg+lJu67rONQrB2wl0YMYmrH8Atr8QszzBmX4rSK1H4tYniwYCXAWedVtdItpZlrNk3Mkylv+u5G44oEYMFbWKX3r+Bd0T93bwMmO9PSSQ3OTFnWura9cpCQy/cKbwd2MOJX1FcvhJbxfQCC57nUAPMG2Hj+nrz4roFal8+VQCH4NuWbgQ4PjAntMBiDzCOEbAIZ3U6ab3+YWIGW8BSHenaYyTGEcJZn9iA9iFNAmgV5k3znDlPUqoTp4COMg9c0szBDtJXzbEq1pMAImn9J1Av4GoxS/LAKmGRjNNl5Hki0Bj9P+8PPt0ouIj56cJOqkl+JK6pzUXaUevFaLCIgtbPkKqSwJw3jJXL4kfTiXg4A2X2gFj0VO+Otdt3sMRvFyV/RqG/l+G/Zn+JqlYY6E9my2VswyRkCwwY1KBu1j/GVhINuNH8kAIYqfY5rmhhRmOxj2vOMvD+RXkU6CipnaAaVe76Jdsu/8e65Sf7KqvkVbWAXARZKz4fN5cKyYXHMUthSSv1Zc6cJmc76el/5HOxwRO+fNS5gOpoAC80vP+Dif+0T6ngOXzhecXEgJCGhaEsJTluexw9Ph3IgeTEfe/4lnpSZWOI+wmMh4zjUfVnehRS8ADmOUujE="
  matrix:
    - IMAGE="kalemena/cura" VERSION="1.0" REPO="kalemena/cura"

before_script:
  - docker pull ${IMAGE}:${VERSION} || true

script:
  - |
    docker build --pull --cache-from ${IMAGE}:${VERSION} \
      -t ${IMAGE}:${VERSION} \
      -f ./software/cura/Dockerfile \
      --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
      --build-arg VCS_REF=`git rev-parse --short HEAD` \
      --build-arg VERSION=`cat VERSION` .
  - docker tag ${IMAGE}:${VERSION} ${IMAGE}:latest
  - docker ps -a
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: docker push ${IMAGE}:${VERSION}; docker push ${IMAGE}:latest
  on:
    branch: master
