sudo: required

services:
  - docker

env:
  global:
    - REGISTRY_USER=kalemena
    - secure: "MFxwGB4oNU/977imIpH/LWCgWBfZohhoIkOx0NZHaTodqGkSt/Vjz2u3pI1AJejTQdCWrDDkqO8T2ucAbrNf+8b3/F1a6wqixgTa9RCYs1HkqKXIdKTK77O6cVSPk+fa5WumaurbdM9+Ac2xrNBVPpGyebqocqMIc/anqyizMrtDyO6kini4wax/PwfkbaaQwZ3DKYxpB6cKYWu3QrY42tXXLqZ2W+Gw2nyW9y3ITmKXdpy5WJ+Gm109g281U9rH/IMnevjneQ87nHDJHmXNQNxL3gy6LKn9jhr6QguOSPq8xLv2shiMh17guA4iRNvMrKlQyQDOKRceUbsvk0fmj7uiyxfNUnr7BekDO+DPhz6gB6mT29XIQgK7bmhLFR1CElWU6aUiuDWy8Rnu166Lw+7UhMSJRuKnjjcf+YEm6xbstLZnK6LUDrn6EgQ1R8BUWUnL3vPy7eBsZT+RJQJkIHwdChC6nyL8bzj1HNlQJ/ZAV7b2Q82dKCxJ9agIh6zmI4COQl0B67qwObdo4jfTd+sjbkP6zCwkSAkBIVXkiWE1Tmb9SRs1VbEPAIJ7dfOmIpsUqR9wc0QRupb5SfRTN+UBDT6oPVv3BSVBPtAA6/4NqWEhgJh2HjlkOD9K9IvyGj04Z2GxQCqejAq347A2sJgI4ihXMejrhb2UqR5p8l4="
  matrix:
    - IMAGE="kalemena/cura" VERSION="1.0" REPO="kalemena/cura"

before_script:
  - docker pull ${IMAGE}:${VERSION} || true

script:
  - |
    docker build --pull --cache-from ${IMAGE}:${VERSION} \
      -t ${IMAGE}:${VERSION} \
      -f ./software/cura/Dockerfile \
      --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
      --build-arg VCS_REF=`git rev-parse --short HEAD` \
      --build-arg VERSION=`cat VERSION` .scripts/
  - docker tag ${IMAGE}:${VERSION} ${IMAGE}:latest
  - docker ps -a
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: docker push ${IMAGE}; docker push ${IMAGE}:latest
  on:
    branch: master
