:toc:

ifdef::env-github[]
image:https://travis-ci.org/kalemena/3dprinting.svg[Travis build status, link=https://travis-ci.org/kalemena/cura]
image:https://images.microbadger.com/badges/version/kalemena/cura.svg[Docker Version, link=https://microbadger.com/images/kalemena/cura]
image:https://images.microbadger.com/badges/image/kalemena/cura.svg[Docker Hub, link=https://hub.docker.com/r/kalemena/cura/tags]
endif::[]

Tooling &amp; Tips for 3d printing

## Printer model

Below is used together with Creality Ender-3 model.

Ender-3 is easy to mount, with ~1h effort.

There are no specific configuration after, because Cura can use "CR-10" defaults, with only changing printer XYZ size.

### Enhancements

* Filament
** [X] link:https://www.thingiverse.com/thing:3052488[Roller Guide]

IMPORTANT: MUST HAVE for noise reduction: Noise goes from "noisy dental care room" to "tower PC loud FAN"

* Noise and smoothness
** [X] link:https://letsprint3d.net/2018/07/07/how-to-install-stepper-motor-dampers-ender-3/[Motors Dampers]

* link:https://www.amazon.fr/dp/B06ZYG3K2Z/ref=psdc_2908498031_t1_B01MV40Z0L?th=1[Head]

* Head Fan

www.thingiverse.com/thing:2759439
https://www.thingiverse.com/thing:2879538
https://www.thingiverse.com/thing:3092044

* Fan

https://www.amazon.fr/gp/product/B0119SLG18/ref=as_li_ss_tl?smid=A1X6FK5RDHNB96&psc=1&linkCode=sl1&tag=wish052-21&linkId=498c18dfc84c318d4be02d8940303ac7


## Material

Up to now, I use only SUNLU wires (from Amazon), so it is not clear is other wires are better or not.

This wire is good.

* PLA+ Gray: *EASY*
** Nozzle 210°C
** Plate 40°C

* PLA+ Carbon Fiber: *DIFFICULT*
** Nozzle 225°C
** Plate 60°C

* PETG+ White: *VERY GOOD FINISH, difficult INFILL*
** Nozzle 250°C 
** Plate 80°C
** Enable "coarsing"
** Reduced "infill speed"

## Software

### OpenSCAD

```bash
$ sudo add-apt-repository ppa:openscad/releases
$ sudo apt-get install openscad
```

### Cura

Cura engine is probably best tool for slicing.

https://download.ultimaker.com/current/Cura-3.5.0.AppImage

https://download.ultimaker.com/current

To run CuraEngine:

```bash
$ sudo apt-get install cura
$ sudo cura &
```

Using docker:

```bash
#!/bin/sh
XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth
sudo docker run -ti \
    -v /etc/passwd:/etc/passwd:ro \
    -v /etc/group:/etc/group:ro \
    -v $HOME:$HOME \
    -v $XSOCK:$XSOCK \
    -v $XAUTH:$XAUTH \
    -e XAUTHORITY=$XAUTH \
    -e DISPLAY \
    --user $UID:$GROUPS \
    kalemena/cura
```

### Repetier

Repetier Host is nice, includes Cura (although it looks using Cura directly gives better results).

### OctoPrint

Find link here:
https://github.com/OctoPrint/docker
https://hub.docker.com/r/rbartl/docker-octoprint/

## Model

Best place to find model is Thingiverse.

Find few of my models under [sub-folder models](models)


